title: Introduction to Computing
description: >-
  iTELL deployment of David Joyner's Introduction to Computing, 1st Edition.
footer: A project by the Language and Educational Analytics Research (Lear)Lab
favicon: /images/avatars/favicon.png
